version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    ports:
      - '80:8079'
    environment:
      - reschedule=on-node-failure
  catalogue:
    image: weaveworksdemos/catalogue
    environment:
      - reschedule=on-node-failure
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: weaveworksdemos/carts
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  carts-db:
    image: mongo
    environment:
      - reschedule=on-node-failure
  orders:
    image: weaveworksdemos/orders
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  orders-db:
    image: mongo
    environment:
      - reschedule=on-node-failure
  shipping:
    image: weaveworksdemos/shipping
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  rabbitmq:
    image: rabbitmq:3.6.8
    environment:
      - reschedule=on-node-failure
  payment:
    image: weaveworksdemos/payment
    environment:
      - reschedule=on-node-failure
  user:
    image: weaveworksdemos/user
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
  user-db:
    image: weaveworksdemos/user-db
    environment:
      - reschedule=on-node-failure
  user-sim:
    image: weaveworksdemos/load-test
    command: "-d 60 -r 200 -c 2 -h front-end"
