---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: sock-shop
spec:
  scaleRef:
    kind: Deployment
    name: user
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
